#!/usr/bin/env python3
"""Render local-only Lidarr and slusk configuration from testenv/.env."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path
import re
import sys
import xml.etree.ElementTree as ET


def load_env(path: Path) -> dict[str, str]:
    values = dict(os.environ)
    for raw_line in path.read_text().splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[7:]
        key, separator, value = line.partition("=")
        if not separator:
            raise ValueError(f"invalid line in {path}: {raw_line!r}")
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key.strip()] = value
    return values


def required(env: dict[str, str], key: str) -> str:
    value = env.get(key, "").strip()
    if not value or value.startswith("CHANGE_ME"):
        raise ValueError(f"set {key} to a dedicated test account in testenv/.env")
    return value


def toml_string(value: str) -> str:
    # JSON strings use the same escaping rules needed by TOML basic strings.
    return json.dumps(value)


def write_lidarr_config(runtime: Path, api_key: str) -> None:
    directory = runtime / "lidarr"
    directory.mkdir(parents=True, exist_ok=True)
    directory.chmod(0o755)
    path = directory / "config.xml"
    if path.exists():
        # Preserve Lidarr-managed settings between normal `up` calls. `reset`
        # removes runtime first and therefore recreates this file from scratch.
        path.chmod(0o644)
        return

    root = ET.Element("Config")
    values = {
        "BindAddress": "*",
        "Port": "8686",
        "SslPort": "6868",
        "EnableSsl": "False",
        "LaunchBrowser": "False",
        "ApiKey": api_key,
        "AuthenticationMethod": "None",
        "AuthenticationRequired": "Enabled",
        "Branch": "master",
        "LogLevel": "info",
        "UrlBase": "",
        "InstanceName": "slusk PR lab",
        "UpdateMechanism": "Docker",
    }
    for key, value in values.items():
        ET.SubElement(root, key).text = value
    ET.ElementTree(root).write(path, encoding="utf-8", xml_declaration=True)
    path.chmod(0o644)


def write_slusk_config(runtime: Path, env: dict[str, str]) -> None:
    directory = runtime / "slusk"
    directory.mkdir(parents=True, exist_ok=True)
    directory.chmod(0o755)
    path = directory / "config.toml"

    backend = env.get("SLUSK_BACKEND", "soulseek").strip()
    if backend not in {"slskd", "soulseek"}:
        raise ValueError("SLUSK_BACKEND must be 'slskd' or 'soulseek'")

    native_user = required(env, "SLUSK_SOULSEEK_USERNAME")
    native_password = required(env, "SLUSK_SOULSEEK_PASSWORD")
    listen_port = env.get("SLUSK_LISTEN_PORT", "50301").strip()
    if not re.fullmatch(r"[1-9][0-9]{0,4}", listen_port) or int(listen_port) > 65535:
        raise ValueError("SLUSK_LISTEN_PORT must be a port from 1 to 65535")

    config = f'''# Generated by testenv/render_config.py. Edit testenv/.env instead.
[lidarr]
url = "http://lidarr:8686"
api_key = {toml_string(env.get("LIDARR_API_KEY", "lidarr-pr-lab-api-key-00000001"))}

[slskd]
url = "http://slskd:5030"
api_key = {toml_string(env.get("SLSKD_API_KEY", "slskd-pr-lab-api-key-00000001"))}

[pipeline]
backend = {toml_string(backend)}
max_candidates_per_album = 5
transfer_deadline = "10m"
stall_timeout = "2m"
search_timeout = "20s"
min_bitrate = 192
max_inflight_per_peer = 3
max_transfer_retries = 3
max_active = 10
max_retries = 3
backoff_base = "30s"
backoff_cap = "5m"
candidate_ttl = "1h"
failed_revive_after = "10m"
stuck_after = "10m"
tick_timeout = "2m"
import_confirm_timeout = "3m"
wanted_sync_interval = "15s"
discovery_interval = "10s"
selecting_interval = "5s"
downloading_interval = "5s"
importing_interval = "10s"
manual_import_timeout = "10m"
import_retry_cooldown = "30s"

[pipeline.weights]
format = 1.0
bitrate = 0.5
reliability = 0.8
file_count = 1.0
known_user = 1.0

[store]
dsn = "postgres://slusk:slusk-test@postgres:5432/slusk?sslmode=disable"

[observ]
auth_token = {toml_string(env.get("SLUSK_OBSERV_TOKEN", "slusk-pr-lab-observ-token-0001"))}
listen_addr = "0.0.0.0:9090"
log_level = "debug"

[paths]
slskd_complete_dir = "/music/slskd-downloads"

# Identify-a-search-result against MusicBrainz (issue #321). Without this
# section the /api/identify/* endpoints answer 503 and the modal can only ever
# show its "unavailable" state, so the lab cannot exercise the feature at all.
#
# contact goes into the User-Agent MusicBrainz's usage policy requires. It is
# the repo URL rather than an address, which the policy accepts and which stays
# honest without putting anyone's mailbox in a generated file. The 1 req/s
# limiter is the client's own, so the lab cannot get the shared IP blocked by
# clicking around.
[musicbrainz]
contact = {toml_string(env.get("SLUSK_MUSICBRAINZ_CONTACT", "https://gitea.shcizo.se/shcizo/slusk"))}
'''
    config += f'''
[soulseek]
server_address = "server.slsknet.org:2242"
username = {toml_string(native_user)}
password = {toml_string(native_password)}
listen_addr = "0.0.0.0:{listen_port}"
upload_slots = 2

# Sharing is what makes the lab usable for upload and share testing: without a
# share the client is a pure leech, /api/shares reports nothing and no peer can
# ever queue a file from it. The path is the read-only mount of
# SLUSK_SHARE_DIR (see compose.yml), never Lidarr's root folder.
[[soulseek.shared_folders]]
name = "Lab"
path = "/music/share"
'''
    path.write_text(config)
    path.chmod(0o644)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--env", type=Path, required=True)
    parser.add_argument("--runtime", type=Path, required=True)
    args = parser.parse_args()

    try:
        env = load_env(args.env)
        args.env.chmod(0o600)
        required(env, "SLSKD_SOULSEEK_USERNAME")
        required(env, "SLSKD_SOULSEEK_PASSWORD")
        write_lidarr_config(args.runtime, env.get("LIDARR_API_KEY", "lidarr-pr-lab-api-key-00000001"))
        write_slusk_config(args.runtime, env)
    except (OSError, ValueError) as exc:
        print(f"configuration error: {exc}", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
