-- 0001_baseline_schema.sql
--
-- This is the immutable baseline migration: it is a verbatim copy of the
-- schema.sql that this project ran (idempotently, on every startup) before
-- migrations/#71 introduced ordered, versioned, transactional migrations.
-- Every database that has ever run this app has already had this exact SQL
-- text applied, so there is no need to reconstruct "true" historical
-- incremental migrations here - this file simply captures the pre-existing
-- desired end-state as migration version 1.
--
-- Once this file is merged, NEVER edit it - always add a new migration file
-- (0002_..., 0003_..., ...) instead. Editing a migration that has already run
-- against a real database means that database's schema_migrations row for
-- this version no longer reflects what actually ran there.

CREATE TABLE IF NOT EXISTS album_jobs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lidarr_album_id  BIGINT NOT NULL,
    state            TEXT NOT NULL,
    candidates_tried BIGINT NOT NULL DEFAULT 0,
    next_attempt_at  TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    title            TEXT NOT NULL DEFAULT '',
    artist_name      TEXT NOT NULL DEFAULT '',
    release_date     TEXT NOT NULL DEFAULT '',
    artist_id        BIGINT NOT NULL DEFAULT 0,
    UNIQUE(lidarr_album_id)
);

-- candidates: a candidate is its own attempt (NEW → ACTIVE → SUCCEEDED|FAILED),
-- with the search result's file list cached as JSONB so Selecting can enqueue
-- without re-searching. Created before transfers below since transfers'
-- candidate_id FK (added further down, guarded) targets this table.
CREATE TABLE IF NOT EXISTS candidates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_job_id        BIGINT NOT NULL REFERENCES album_jobs(id),
    username            TEXT NOT NULL,
    score               DOUBLE PRECISION NOT NULL,
    files               JSONB NOT NULL,
    state               TEXT NOT NULL,
    fail_reason         TEXT NOT NULL DEFAULT '',
    import_submitted_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);

-- transfers.candidate_id is NOT NULL but deliberately has no inline REFERENCES:
-- the guarded FK add further down (transfers_candidate_id_fkey) is the single
-- source of that constraint, so a fresh database and a database migrated from
-- an older schema version end up in the same state.
CREATE TABLE IF NOT EXISTS transfers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    candidate_id     BIGINT NOT NULL,
    slskd_id         TEXT NOT NULL DEFAULT '',
    username         TEXT NOT NULL,
    filename         TEXT NOT NULL,
    state            TEXT NOT NULL,
    bytes_done       BIGINT NOT NULL DEFAULT 0,
    bytes_total      BIGINT NOT NULL DEFAULT 0,
    deadline         TIMESTAMPTZ NOT NULL,
    last_progress_at TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ NOT NULL,
    retries          BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT transfers_candidate_username_filename_key
        UNIQUE(candidate_id, username, filename)
);

-- Pre-rewrite migration, and it MUST run before idx_transfers_candidate below:
-- on a database where transfers still has attempt_id, CREATE INDEX IF NOT
-- EXISTS only guards the index NAME - Postgres still resolves the column list,
-- so an index on candidate_id would abort the apply (and the boot) unless the
-- rename has already happened. On a fresh database (transfers created above
-- already has candidate_id) every statement here is a no-op.
ALTER TABLE transfers DROP CONSTRAINT IF EXISTS transfers_attempt_id_fkey;

-- Postgres has no "RENAME COLUMN IF EXISTS" form, hence the DO block guard -
-- it is a no-op once the column has already been renamed (or was never named
-- attempt_id to begin with, as on a fresh database).
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name='transfers' AND column_name='attempt_id') THEN
        ALTER TABLE transfers RENAME COLUMN attempt_id TO candidate_id;
    END IF;
END $$;

-- The original write-ahead schema made (username, filename) globally unique.
-- That lets a second job attempting the same remote file silently move the
-- first job's transfer row to its own candidate via ON CONFLICT, leaving the
-- first DOWNLOADING job with an incomplete set. Idempotently replace that key
-- with candidate-scoped ownership after the legacy candidate_id rename above.
-- The old global key guarantees existing data cannot conflict while the new
-- key is added.
ALTER TABLE transfers DROP CONSTRAINT IF EXISTS transfers_username_filename_key;
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint
                   WHERE conname = 'transfers_candidate_username_filename_key') THEN
        ALTER TABLE transfers ADD CONSTRAINT transfers_candidate_username_filename_key
            UNIQUE (candidate_id, username, filename);
    END IF;
END $$;

-- Only one candidate may own an unsettled remote file at a time. This keeps
-- username+filename crash fallback unambiguous without imposing global
-- uniqueness on terminal history, which later candidates/jobs may legitimately
-- retry. A conflicting activation fails inside its transaction and rolls back.
CREATE UNIQUE INDEX IF NOT EXISTS idx_transfers_live_remote_owner
    ON transfers(username, filename)
    WHERE state IN ('PENDING', 'QUEUED', 'IN_PROGRESS', 'STALLED');

-- Pre-rewrite databases had these indexes on the now-gone candidate_attempts
-- table and the old attempt_id-named transfers index; drop them on upgrade.
DROP INDEX IF EXISTS idx_attempts_job;
DROP INDEX IF EXISTS idx_transfers_attempt;

CREATE INDEX IF NOT EXISTS idx_transfers_slskd_id ON transfers(slskd_id);
CREATE INDEX IF NOT EXISTS idx_jobs_state ON album_jobs(state);

-- Covering indexes for the per-job "latest candidate" / "latest transfer"
-- correlated subqueries (store/dashboard.go jobViewSelect) and the engine's
-- CandidatesForJob/TransfersForCandidate lookups. Without these, each subquery
-- is a full table scan executed once per album_jobs row, which at a few
-- thousand jobs turned one dashboard /api/jobs request into tens of seconds
-- of CPU.
CREATE INDEX IF NOT EXISTS idx_candidates_job ON candidates(album_job_id, state);
CREATE INDEX IF NOT EXISTS idx_transfers_candidate ON transfers(candidate_id, updated_at);

-- idx_candidates_job_created backs the "latest candidate per job" correlated
-- subquery (jobViewSelect above) and CandidatesForJob's per-job listing, both
-- of which filter on album_job_id and order by created_at. idx_candidates_job
-- (album_job_id, state) does not cover that ordering, so without this index
-- each subquery still full-scans a job's candidates to find the newest one.
CREATE INDEX IF NOT EXISTS idx_candidates_job_created ON candidates(album_job_id, created_at);

-- known_users and artist_user_reliability hold the running success/fail history
-- of Soulseek peers, used to score-boost known-good peers (and suppress
-- consistently-failing ones) in future candidate ranking. CRITICAL: these two
-- tables are the ONLY peer history that survives a failed-album retry.
-- ResetJobForRetry DELETEs a job's candidates (and transfers) in a
-- transaction, so peer history must NOT be derived/recomputed from candidates -
-- it is written incrementally at attempt completion (RecordAttemptOutcome) and
-- kept here across retry cycles. Decay is computed in Go from the *_at
-- timestamps at ranking time, so nothing here is a pre-aged score.

-- known_users is the global reliability per username (unique across all artists).
CREATE TABLE IF NOT EXISTS known_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    success_count   BIGINT NOT NULL DEFAULT 0,
    fail_count      BIGINT NOT NULL DEFAULT 0,
    last_success_at TIMESTAMPTZ,
    last_fail_at    TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL
);

-- artist_user_reliability is a junction table: one row per (artist, user) pair,
-- holding that peer's history for that specific artist (the strong signal that
-- takes precedence over the global known_users row).
CREATE TABLE IF NOT EXISTS artist_user_reliability (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id       BIGINT NOT NULL,
    user_id         BIGINT NOT NULL REFERENCES known_users(id),
    success_count   BIGINT NOT NULL DEFAULT 0,
    fail_count      BIGINT NOT NULL DEFAULT 0,
    last_success_at TIMESTAMPTZ,
    last_fail_at    TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL,
    UNIQUE(artist_id, user_id)
);

-- job_events is an append-only audit trail of key pipeline decisions (search,
-- candidate selection, attempt outcomes, imports), surfaced by the dashboard's
-- Händelser (event timeline) tab and per-job detail panel. Pruned by the
-- engine loop on a fixed retention window (see Store.PruneJobEvents).
CREATE TABLE IF NOT EXISTS job_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_job_id  BIGINT NOT NULL,
    event         TEXT NOT NULL,
    detail        TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_job_events_job ON job_events(album_job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_job_events_created ON job_events(created_at);

-- Pipeline rewrite (spec 2026-07-06): backoff/retry live on the job as data,
-- not as states. failed_at drives WantedSync's 30-day revival of FAILED jobs.
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS retries    BIGINT NOT NULL DEFAULT 0;
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS not_before TIMESTAMPTZ;
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS failed_at  TIMESTAMPTZ;

-- The attempt_id → candidate_id rename and old-index drops run much earlier
-- in this file (they must precede idx_transfers_candidate); what remains here
-- is only work on databases that ran a pre-rewrite version of this file. On a
-- fresh database transfers is already created in its final shape above, so
-- both guards below are no-ops.

-- Postgres has no "ADD CONSTRAINT IF NOT EXISTS" form, hence the guard.
-- NOT VALID: pre-existing rows are wiped by scripts/clean-slate-pipeline.sh
-- ahead of this deploy anyway, so there is nothing to validate against.
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'transfers_candidate_id_fkey') THEN
        ALTER TABLE transfers ADD CONSTRAINT transfers_candidate_id_fkey
            FOREIGN KEY (candidate_id) REFERENCES candidates(id) NOT VALID;
    END IF;
END $$;

-- candidate_attempts is gone: candidates (above) replaces it in the pipeline
-- rewrite, and the legacy engine that wrote it is deleted.
DROP TABLE IF EXISTS candidate_attempts;

-- Import-pipeline robustness (spec 2026-07-19): the album's valid track-count
-- band across all Lidarr releases (editions), cached by Discovery at search
-- time and read by Importing's coverage gate. (0,0) means unknown.
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS min_track_count BIGINT NOT NULL DEFAULT 0;
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS max_track_count BIGINT NOT NULL DEFAULT 0;
