-- search_passes records one row per completed Discovery search cycle (a
-- "pass"): searched = wanted albums examined, matched = albums that found
-- viable candidates and advanced to SELECTING. Backs GET /api/charts (issue
-- #88). Pruned on the same fixed 30-day window as job_events (see
-- Store.PruneSearchPasses).
CREATE TABLE IF NOT EXISTS search_passes (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at  TIMESTAMPTZ NOT NULL,
    finished_at TIMESTAMPTZ NOT NULL,
    searched    INT NOT NULL,
    matched     INT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_search_passes_started ON search_passes(started_at);
