-- throughput_minutes records one row per completed download-throughput
-- minute (issue #157): avg/max bytes-per-second and the peak number of
-- concurrently active downloads observed during that minute, sampled by the
-- native soulseek client's throughput meter (see soulseek.throughputMeter)
-- and drained by cmd/slusk's throughput recorder. Backs the Overview
-- charts' throughput history. UNIQUE(minute) both prevents duplicate rows for
-- the same minute and is the index Store.PruneThroughputMinutes' range scan
-- uses, so no separate index is added. Pruned on the same fixed 30-day
-- window as search_passes/job_events (see Store.PruneThroughputMinutes).
CREATE TABLE IF NOT EXISTS throughput_minutes (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    minute            TIMESTAMPTZ NOT NULL UNIQUE,
    avg_bytes_per_sec BIGINT NOT NULL,
    max_bytes_per_sec BIGINT NOT NULL,
    max_active        INT NOT NULL,
    samples           INT NOT NULL
);
