-- private_messages persists every Soulseek private message, both directions
-- (issue #183). server_message_id is the server-assigned id echoed back in
-- MessageAcked: it is the dedup key for a message the server redelivers
-- because a crash or a failed ack write landed between persisting the
-- message and acking it (see Store.RecordIncomingMessage), and is NULL for
-- outgoing messages and for the defensive id==0 case (a server that sent no
-- id at all). There is no pruning here, deliberately: this table is the only
-- durable copy of a conversation's history, and the Soulseek protocol
-- delivers an offline message exactly once per login - the ack is what stops
-- redelivery, not a retention window, so trimming rows would destroy mail
-- with no way to recover it from the server.
CREATE TABLE IF NOT EXISTS private_messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          TEXT NOT NULL,
    direction         TEXT NOT NULL,
    body              TEXT NOT NULL,
    server_message_id BIGINT,
    is_admin          BIGINT NOT NULL DEFAULT 0,
    sent_at           TIMESTAMPTZ NOT NULL,
    received_at       TIMESTAMPTZ NOT NULL,
    read_at           TIMESTAMPTZ
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_private_messages_server_id
    ON private_messages (server_message_id)
    WHERE server_message_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_private_messages_thread
    ON private_messages (username, sent_at DESC, id DESC);

CREATE INDEX IF NOT EXISTS idx_private_messages_unread
    ON private_messages (username)
    WHERE read_at IS NULL;
