-- Durable history of finished uploads to other peers (issue #325). Everything
-- about an upload used to live only in the native client's in-memory
-- uploadManager, which is rebuilt from nothing on every reconnect, so a restart
-- erased all trace of what we had shared. One row is appended here per upload
-- once its outcome is decided — never from the streaming hot path.
--
-- filename is the VIRTUAL share path (backslash-separated, rooted at the
-- configured share name), never the local filesystem path. The virtual path is
-- already visible to every peer that browses us, so there is nothing to redact;
-- the local path is a different matter and must never be written here. The same
-- rule governs detail: it carries a short fixed reason string chosen by the
-- caller, never a raw err.Error(), because upload errors routinely wrap
-- *os.PathError and would leak a local path into an API response (the identical
-- trap registerShares' rescan branch already avoids).
--
-- No secondary index on purpose. The only read path is keyset pagination on
-- id DESC, which the primary key already serves. An index on (username, id DESC)
-- belongs with the first per-peer filter, not before it.
CREATE TABLE IF NOT EXISTS upload_history (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username          TEXT NOT NULL,
    filename          TEXT NOT NULL,
    size              BIGINT NOT NULL,
    -- bytes_sent counts only what this attempt put on the wire: a resumed
    -- upload starts at the peer's requested offset, and storing the absolute
    -- counter would silently overstate both volume and speed.
    bytes_sent        BIGINT NOT NULL,
    -- bytes_sent over the streaming phase's own duration, excluding queue and
    -- negotiation time. Zero on a rejected row, where it is a true measurement
    -- of nothing rather than a missing one — a UI must render that as "—",
    -- not as "0 B/s".
    avg_bytes_per_sec BIGINT NOT NULL,
    -- 'completed', 'aborted' or 'rejected' (core.UploadStatus). Deliberately
    -- not a CHECK constraint or an enum: the reason lives in detail as free
    -- text so that a new abort path in the client never needs a migration.
    status            TEXT NOT NULL,
    detail            TEXT,
    -- started_at is when the job began running, so finished_at - started_at
    -- includes queueing and negotiation. Use avg_bytes_per_sec for speed.
    started_at        TIMESTAMPTZ NOT NULL,
    finished_at       TIMESTAMPTZ NOT NULL
);
