-- job_download_folders records the local folder a job's downloads are written
-- into, at the moment they are written, so cleanup can look the folder up
-- instead of reconstructing it afterwards from whatever transfer rows happen to
-- still exist (issue #314).
--
-- The column holds a single path element ("leaf"), not a path: both backends'
-- DeleteDownloadFolder takes a relative subdirectory name, and slskd's local
-- path lives inside slskd's own container rather than under slusk's
-- complete_dir, so an absolute path would be meaningless for that backend. The
-- CHECK is what makes "the register can never point outside the download root"
-- an invariant of the table rather than something every consumer must re-check.
--
-- The row's lifetime is the job's, not the search cycle's: ResetJobToWanted and
-- ForceSearchJob delete candidates/transfers but deliberately leave these rows
-- alone, which is the whole point — that deletion is what orphaned earlier
-- cycles' folders. Only DeleteJob removes them.
CREATE TABLE IF NOT EXISTS job_download_folders (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_job_id BIGINT NOT NULL REFERENCES album_jobs(id),
    leaf         TEXT NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    cleaned_at   TIMESTAMPTZ,
    CONSTRAINT job_download_folders_leaf_is_one_element
        CHECK (leaf <> '' AND leaf !~ '[/\\]' AND leaf NOT IN ('.', '..')),
    CONSTRAINT job_download_folders_job_leaf_key UNIQUE (album_job_id, leaf)
);

CREATE INDEX IF NOT EXISTS job_download_folders_job_uncleaned_idx
    ON job_download_folders (album_job_id) WHERE cleaned_at IS NULL;

-- Backfill for jobs that are still alive at deploy time, so the switchover has
-- no window in which a running job has written to disk but registered nothing.
-- This is not the "repair orphaned folders" work the issue puts out of scope:
-- terminal jobs are deliberately skipped, and nothing on disk is inspected.
--
-- The conditions reproduce commonLeaf's exactly (one distinct directory across
-- a candidate's transfers, no "."/".."), so the backfill can only ever produce
-- a row today's cleanup would already have derived. A wrong row here is inert
-- rather than destructive: the CHECK keeps it inside the download root, and a
-- folder that is not on disk makes both quarantineFolder (os.Stat) and
-- cleanupFolder (ErrRemoteNotFound) no-op.
--
-- The terminal state list mirrors core.AlbumJobState.PipelineTerminal.
WITH dirs AS (
    SELECT c.album_job_id,
           c.id AS candidate_id,
           regexp_replace(replace(t.filename, '\', '/'), '/[^/]*$', '') AS dir
    FROM candidates c
    JOIN album_jobs j ON j.id = c.album_job_id
    JOIN transfers  t ON t.candidate_id = c.id
    WHERE j.state NOT IN ('DONE', 'FAILED', 'CANCELLED', 'NOT_IMPORTED')
      -- Require a separator. regexp_replace leaves a string with no '/'
      -- untouched, so without this a peer sharing a track at its share root
      -- ("bonus.flac") backfills leaf = "bonus.flac" — a FILE registered as a
      -- folder, which cleanupFolder would hand to a recursive delete. Go's
      -- commonLeaf returns "" there (path.Dir gives "."), and this clause is
      -- what reproduces that.
      AND replace(t.filename, '\', '/') LIKE '%/%'
),
single AS (
    SELECT album_job_id, min(dir) AS dir
    FROM dirs
    GROUP BY album_job_id, candidate_id
    HAVING count(DISTINCT dir) = 1
)
INSERT INTO job_download_folders (album_job_id, leaf, created_at)
SELECT DISTINCT album_job_id, regexp_replace(dir, '^.*/', ''), now()
FROM single
WHERE dir NOT IN ('.', '/', '')
  AND regexp_replace(dir, '^.*/', '') NOT IN ('.', '..', '.failed')
ON CONFLICT ON CONSTRAINT job_download_folders_job_leaf_key DO NOTHING;
