// Code generated by "stringer -type CodeInit -trimprefix Code"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodePeerInit-1]
	_ = x[CodePierceFirewall-0]
}

const _CodeInit_name = "PierceFirewallPeerInit"

var _CodeInit_index = [...]uint8{0, 14, 22}

func (i CodeInit) String() string {
	if i < 0 || i >= CodeInit(len(_CodeInit_index)-1) {
		return "CodeInit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _CodeInit_name[_CodeInit_index[i]:_CodeInit_index[i+1]]
}
