// Code generated by "stringer -type Code -trimprefix Code"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeFileSearchResponse-9]
	_ = x[CodeFolderContentsRequest-36]
	_ = x[CodeFolderContentsResponse-37]
	_ = x[CodePlaceInQueueRequest-51]
	_ = x[CodePlaceInQueueResponse-44]
	_ = x[CodeQueueUpload-43]
	_ = x[CodeSharedFileListResponse-5]
	_ = x[CodeSharedFileListRequest-4]
	_ = x[CodeTransferRequest-40]
	_ = x[CodeTransferResponse-41]
	_ = x[CodeUploadDenied-50]
	_ = x[CodeUploadFailed-46]
	_ = x[CodeUserInfoRequest-15]
	_ = x[CodeUserInfoResponse-16]
}

const (
	_Code_name_0 = "SharedFileListRequestSharedFileListResponse"
	_Code_name_1 = "FileSearchResponse"
	_Code_name_2 = "UserInfoRequestUserInfoResponse"
	_Code_name_3 = "FolderContentsRequestFolderContentsResponse"
	_Code_name_4 = "TransferRequestTransferResponse"
	_Code_name_5 = "QueueUploadPlaceInQueueResponse"
	_Code_name_6 = "UploadFailed"
	_Code_name_7 = "UploadDeniedPlaceInQueueRequest"
)

var (
	_Code_index_0 = [...]uint8{0, 21, 43}
	_Code_index_2 = [...]uint8{0, 15, 31}
	_Code_index_3 = [...]uint8{0, 21, 43}
	_Code_index_4 = [...]uint8{0, 15, 31}
	_Code_index_5 = [...]uint8{0, 11, 31}
	_Code_index_7 = [...]uint8{0, 12, 31}
)

func (i Code) String() string {
	switch {
	case 4 <= i && i <= 5:
		i -= 4
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 9:
		return _Code_name_1
	case 15 <= i && i <= 16:
		i -= 15
		return _Code_name_2[_Code_index_2[i]:_Code_index_2[i+1]]
	case 36 <= i && i <= 37:
		i -= 36
		return _Code_name_3[_Code_index_3[i]:_Code_index_3[i+1]]
	case 40 <= i && i <= 41:
		i -= 40
		return _Code_name_4[_Code_index_4[i]:_Code_index_4[i+1]]
	case 43 <= i && i <= 44:
		i -= 43
		return _Code_name_5[_Code_index_5[i]:_Code_index_5[i+1]]
	case i == 46:
		return _Code_name_6
	case 50 <= i && i <= 51:
		i -= 50
		return _Code_name_7[_Code_index_7[i]:_Code_index_7[i+1]]
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
