// Code generated by "stringer -type TransferDirection"; DO NOT EDIT.

package peer

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DownloadFromPeer-0]
	_ = x[UploadToPeer-1]
}

const _TransferDirection_name = "DownloadFromPeerUploadToPeer"

var _TransferDirection_index = [...]uint8{0, 16, 28}

func (i TransferDirection) String() string {
	if i < 0 || i >= TransferDirection(len(_TransferDirection_index)-1) {
		return "TransferDirection(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TransferDirection_name[_TransferDirection_index[i]:_TransferDirection_index[i+1]]
}
