// Code generated by "stringer -type=Code -trimprefix=Code"; DO NOT EDIT.

package distributed

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeBranchLevel-4]
	_ = x[CodeBranchRoot-5]
	_ = x[CodeEmbeddedMessage-93]
	_ = x[CodeSearch-3]
}

const (
	_Code_name_0 = "SearchBranchLevelBranchRoot"
	_Code_name_1 = "EmbeddedMessage"
)

var (
	_Code_index_0 = [...]uint8{0, 6, 17, 27}
)

func (i Code) String() string {
	switch {
	case 3 <= i && i <= 5:
		i -= 3
		return _Code_name_0[_Code_index_0[i]:_Code_index_0[i+1]]
	case i == 93:
		return _Code_name_1
	default:
		return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
