// Code generated by "stringer -type Code -trimprefix Code"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[CodeAcceptChildren-100]
	_ = x[CodeAdminMessage-66]
	_ = x[CodeBranchLevel-126]
	_ = x[CodeBranchRoot-127]
	_ = x[CodeCantConnectToPeer-1001]
	_ = x[CodeCantCreateRoom-1003]
	_ = x[CodeChangePassword-142]
	_ = x[CodeCheckPrivileges-92]
	_ = x[CodeConnectToPeer-18]
	_ = x[CodeEmbeddedMessage-93]
	_ = x[CodeExcludedSearchPhrases-160]
	_ = x[CodeFileSearch-26]
	_ = x[CodeGetPeerAddress-3]
	_ = x[CodeGetUserStats-36]
	_ = x[CodeGetUserStatus-7]
	_ = x[CodeGivePrivileges-123]
	_ = x[CodeHaveNoParent-71]
	_ = x[CodeJoinRoom-14]
	_ = x[CodeLeaveRoom-15]
	_ = x[CodeLogin-1]
	_ = x[CodeMessageAcked-23]
	_ = x[CodeMessageUser-22]
	_ = x[CodeMessageUsers-149]
	_ = x[CodeParentMinSpeed-83]
	_ = x[CodeParentSpeedRatio-84]
	_ = x[CodePing-32]
	_ = x[CodePossibleParents-102]
	_ = x[CodePrivateRoomAdded-139]
	_ = x[CodePrivateRoomAddOperator-143]
	_ = x[CodePrivateRoomAddUser-134]
	_ = x[CodePrivateRoomCancelMembership-136]
	_ = x[CodePrivateRoomDisown-137]
	_ = x[CodePrivateRoomOperatorAdded-145]
	_ = x[CodePrivateRoomOperatorRemoved-146]
	_ = x[CodePrivateRoomOperators-148]
	_ = x[CodePrivateRoomRemoved-140]
	_ = x[CodePrivateRoomRemoveOperator-144]
	_ = x[CodePrivateRoomRemoveUser-135]
	_ = x[CodePrivateRoomToggle-141]
	_ = x[CodePrivateRoomUsers-133]
	_ = x[CodePrivilegedUsers-69]
	_ = x[CodeRelogged-41]
	_ = x[CodeResetDistributed-130]
	_ = x[CodeRoomList-64]
	_ = x[CodeRoomSearch-120]
	_ = x[CodeRoomTicker-113]
	_ = x[CodeRoomTickerAdd-114]
	_ = x[CodeRoomTickerRemove-115]
	_ = x[CodeRoomTickerSet-116]
	_ = x[CodeSayChatroom-13]
	_ = x[CodeSendUploadSpeed-121]
	_ = x[CodeSetListenPort-2]
	_ = x[CodeSetStatus-28]
	_ = x[CodeSharedFoldersFiles-35]
	_ = x[CodeUnwatchUser-6]
	_ = x[CodeUserJoinedRoom-16]
	_ = x[CodeUserLeftRoom-17]
	_ = x[CodeUserSearch-42]
	_ = x[CodeWatchUser-5]
	_ = x[CodeWishlistInterval-104]
	_ = x[CodeWishlistSearch-103]
}

const _Code_name = "LoginSetListenPortGetPeerAddressWatchUserUnwatchUserGetUserStatusSayChatroomJoinRoomLeaveRoomUserJoinedRoomUserLeftRoomConnectToPeerMessageUserMessageAckedFileSearchSetStatusPingSharedFoldersFilesGetUserStatsReloggedUserSearchRoomListAdminMessagePrivilegedUsersHaveNoParentParentMinSpeedParentSpeedRatioCheckPrivilegesEmbeddedMessageAcceptChildrenPossibleParentsWishlistSearchWishlistIntervalRoomTickerRoomTickerAddRoomTickerRemoveRoomTickerSetRoomSearchSendUploadSpeedGivePrivilegesBranchLevelBranchRootResetDistributedPrivateRoomUsersPrivateRoomAddUserPrivateRoomRemoveUserPrivateRoomCancelMembershipPrivateRoomDisownPrivateRoomAddedPrivateRoomRemovedPrivateRoomToggleChangePasswordPrivateRoomAddOperatorPrivateRoomRemoveOperatorPrivateRoomOperatorAddedPrivateRoomOperatorRemovedPrivateRoomOperatorsMessageUsersExcludedSearchPhrasesCantConnectToPeerCantCreateRoom"

var _Code_map = map[Code]string{
	1:    _Code_name[0:5],
	2:    _Code_name[5:18],
	3:    _Code_name[18:32],
	5:    _Code_name[32:41],
	6:    _Code_name[41:52],
	7:    _Code_name[52:65],
	13:   _Code_name[65:76],
	14:   _Code_name[76:84],
	15:   _Code_name[84:93],
	16:   _Code_name[93:107],
	17:   _Code_name[107:119],
	18:   _Code_name[119:132],
	22:   _Code_name[132:143],
	23:   _Code_name[143:155],
	26:   _Code_name[155:165],
	28:   _Code_name[165:174],
	32:   _Code_name[174:178],
	35:   _Code_name[178:196],
	36:   _Code_name[196:208],
	41:   _Code_name[208:216],
	42:   _Code_name[216:226],
	64:   _Code_name[226:234],
	66:   _Code_name[234:246],
	69:   _Code_name[246:261],
	71:   _Code_name[261:273],
	83:   _Code_name[273:287],
	84:   _Code_name[287:303],
	92:   _Code_name[303:318],
	93:   _Code_name[318:333],
	100:  _Code_name[333:347],
	102:  _Code_name[347:362],
	103:  _Code_name[362:376],
	104:  _Code_name[376:392],
	113:  _Code_name[392:402],
	114:  _Code_name[402:415],
	115:  _Code_name[415:431],
	116:  _Code_name[431:444],
	120:  _Code_name[444:454],
	121:  _Code_name[454:469],
	123:  _Code_name[469:483],
	126:  _Code_name[483:494],
	127:  _Code_name[494:504],
	130:  _Code_name[504:520],
	133:  _Code_name[520:536],
	134:  _Code_name[536:554],
	135:  _Code_name[554:575],
	136:  _Code_name[575:602],
	137:  _Code_name[602:619],
	139:  _Code_name[619:635],
	140:  _Code_name[635:653],
	141:  _Code_name[653:670],
	142:  _Code_name[670:684],
	143:  _Code_name[684:706],
	144:  _Code_name[706:731],
	145:  _Code_name[731:755],
	146:  _Code_name[755:781],
	148:  _Code_name[781:801],
	149:  _Code_name[801:813],
	160:  _Code_name[813:834],
	1001: _Code_name[834:851],
	1003: _Code_name[851:865],
}

func (i Code) String() string {
	if str, ok := _Code_map[i]; ok {
		return str
	}
	return "Code(" + strconv.FormatInt(int64(i), 10) + ")"
}
