// Code generated by "stringer -type UserStatus -trimprefix Status"; DO NOT EDIT.

package server

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[StatusOffline-0]
	_ = x[StatusAway-1]
	_ = x[StatusOnline-2]
}

const _UserStatus_name = "OfflineAwayOnline"

var _UserStatus_index = [...]uint8{0, 7, 11, 17}

func (i UserStatus) String() string {
	if i < 0 || i >= UserStatus(len(_UserStatus_index)-1) {
		return "UserStatus(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserStatus_name[_UserStatus_index[i]:_UserStatus_index[i+1]]
}
