CREATE TABLE IF NOT EXISTS album_jobs (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lidarr_album_id  BIGINT NOT NULL,
    state            TEXT NOT NULL,
    candidates_tried BIGINT NOT NULL DEFAULT 0,
    next_attempt_at  TIMESTAMPTZ,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    title            TEXT NOT NULL DEFAULT '',
    artist_name      TEXT NOT NULL DEFAULT '',
    release_date     TEXT NOT NULL DEFAULT '',
    artist_id        BIGINT NOT NULL DEFAULT 0,
    UNIQUE(lidarr_album_id)
);

CREATE TABLE IF NOT EXISTS candidate_attempts (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_job_id  BIGINT NOT NULL REFERENCES album_jobs(id),
    username      TEXT NOT NULL,
    score         DOUBLE PRECISION NOT NULL,
    state         TEXT NOT NULL,
    fail_reason   TEXT NOT NULL DEFAULT '',
    backoff_until TIMESTAMPTZ,
    created_at    TIMESTAMPTZ NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS transfers (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id       BIGINT NOT NULL REFERENCES candidate_attempts(id),
    slskd_id         TEXT NOT NULL DEFAULT '',
    username         TEXT NOT NULL,
    filename         TEXT NOT NULL,
    state            TEXT NOT NULL,
    bytes_done       BIGINT NOT NULL DEFAULT 0,
    bytes_total      BIGINT NOT NULL DEFAULT 0,
    deadline         TIMESTAMPTZ NOT NULL,
    last_progress_at TIMESTAMPTZ,
    updated_at       TIMESTAMPTZ NOT NULL,
    retries          BIGINT NOT NULL DEFAULT 0,
    UNIQUE(username, filename)
);

CREATE INDEX IF NOT EXISTS idx_transfers_slskd_id ON transfers(slskd_id);
CREATE INDEX IF NOT EXISTS idx_jobs_state ON album_jobs(state);

-- Covering indexes for the per-job "latest attempt" / "latest transfer"
-- correlated subqueries (store/dashboard.go jobViewSelect) and the engine's
-- AttemptsForJob/TransfersForAttempt lookups. Without these, each subquery is
-- a full table scan executed once per album_jobs row, which at a few thousand
-- jobs turned one dashboard /api/jobs request into tens of seconds of CPU.
CREATE INDEX IF NOT EXISTS idx_attempts_job ON candidate_attempts(album_job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_transfers_attempt ON transfers(attempt_id, updated_at);

-- known_users and artist_user_reliability hold the running success/fail history
-- of Soulseek peers, used to score-boost known-good peers (and suppress
-- consistently-failing ones) in future candidate ranking. CRITICAL: these two
-- tables are the ONLY peer history that survives a failed-album retry.
-- ResetJobForRetry DELETEs a job's candidate_attempts (and transfers) in a
-- transaction, so peer history must NOT be derived/recomputed from attempts -
-- it is written incrementally at attempt completion (RecordAttemptOutcome) and
-- kept here across retry cycles. Decay is computed in Go from the *_at
-- timestamps at ranking time, so nothing here is a pre-aged score.

-- known_users is the global reliability per username (unique across all artists).
CREATE TABLE IF NOT EXISTS known_users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        TEXT NOT NULL UNIQUE,
    success_count   BIGINT NOT NULL DEFAULT 0,
    fail_count      BIGINT NOT NULL DEFAULT 0,
    last_success_at TIMESTAMPTZ,
    last_fail_at    TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL
);

-- artist_user_reliability is a junction table: one row per (artist, user) pair,
-- holding that peer's history for that specific artist (the strong signal that
-- takes precedence over the global known_users row).
CREATE TABLE IF NOT EXISTS artist_user_reliability (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    artist_id       BIGINT NOT NULL,
    user_id         BIGINT NOT NULL REFERENCES known_users(id),
    success_count   BIGINT NOT NULL DEFAULT 0,
    fail_count      BIGINT NOT NULL DEFAULT 0,
    last_success_at TIMESTAMPTZ,
    last_fail_at    TIMESTAMPTZ,
    updated_at      TIMESTAMPTZ NOT NULL,
    UNIQUE(artist_id, user_id)
);

-- job_events is an append-only audit trail of key pipeline decisions (search,
-- candidate selection, attempt outcomes, imports), surfaced by the dashboard's
-- Händelser (event timeline) tab and per-job detail panel. Pruned by the
-- engine loop on a fixed retention window (see Store.PruneJobEvents).
CREATE TABLE IF NOT EXISTS job_events (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_job_id  BIGINT NOT NULL,
    event         TEXT NOT NULL,
    detail        TEXT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_job_events_job ON job_events(album_job_id, created_at);
CREATE INDEX IF NOT EXISTS idx_job_events_created ON job_events(created_at);

-- Pipeline rewrite (spec 2026-07-06): backoff/retry live on the job as data,
-- not as states. failed_at drives WantedSync's 30-day revival of FAILED jobs.
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS retries    BIGINT NOT NULL DEFAULT 0;
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS not_before TIMESTAMPTZ;
ALTER TABLE album_jobs ADD COLUMN IF NOT EXISTS failed_at  TIMESTAMPTZ;

-- candidates replaces candidate_attempts: a candidate is its own attempt
-- (NEW → ACTIVE → SUCCEEDED|FAILED), with the search result's file list cached
-- as JSONB so Selecting can enqueue without re-searching.
CREATE TABLE IF NOT EXISTS candidates (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_job_id        BIGINT NOT NULL REFERENCES album_jobs(id),
    username            TEXT NOT NULL,
    score               DOUBLE PRECISION NOT NULL,
    files               JSONB NOT NULL,
    state               TEXT NOT NULL,
    fail_reason         TEXT NOT NULL DEFAULT '',
    import_submitted_at TIMESTAMPTZ,
    created_at          TIMESTAMPTZ NOT NULL,
    updated_at          TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_candidates_job ON candidates(album_job_id, state);

-- transfers.attempt_id now holds candidate IDs in the pipeline, so the FK to
-- candidate_attempts must go or pipeline writes would violate it. The column
-- itself is renamed to candidate_id below.
ALTER TABLE transfers DROP CONSTRAINT IF EXISTS transfers_attempt_id_fkey;

-- Schema finalization (engine deletion, spec 2026-07-06): transfers now
-- references candidates, renamed from the legacy attempt_id. Postgres has no
-- "RENAME COLUMN IF EXISTS" form, hence the DO block guard - it is a no-op
-- once the column has already been renamed on a prior startup.
DO $$ BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.columns
               WHERE table_name='transfers' AND column_name='attempt_id') THEN
        ALTER TABLE transfers RENAME COLUMN attempt_id TO candidate_id;
    END IF;
END $$;

-- Postgres has no "ADD CONSTRAINT IF NOT EXISTS" form either, hence the guard.
-- NOT VALID: pre-existing rows are wiped by scripts/clean-slate-pipeline.sh
-- ahead of this deploy anyway, so there is nothing to validate against.
DO $$ BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'transfers_candidate_id_fkey') THEN
        ALTER TABLE transfers ADD CONSTRAINT transfers_candidate_id_fkey
            FOREIGN KEY (candidate_id) REFERENCES candidates(id) NOT VALID;
    END IF;
END $$;

-- candidate_attempts is gone: candidates (above) replaces it in the pipeline
-- rewrite, and the legacy engine that wrote it is deleted.
DROP TABLE IF EXISTS candidate_attempts;
