// Command sqlite2pg is a one-off migration tool that copies an existing
// slskdarr SQLite database into a fresh PostgreSQL database. It applies the
// current store schema to the target, refuses to run if any target table
// already has rows, and copies every table in foreign-key order preserving
// primary keys, then resets each identity sequence so future inserts don't
// collide.
//
// Usage:
//
//	sqlite2pg -sqlite /data/slskdarr.db -pg 'postgres://slskdarr:password@localhost:5432/slskdarr?sslmode=disable'
package main

import (
	"database/sql"
	"flag"
	"fmt"
	"log"
	"os"
	"strings"

	_ "github.com/jackc/pgx/v5/stdlib"
	_ "modernc.org/sqlite"

	"github.com/samuelenocsson/slskdarr/internal/store"
)

// tables lists every table in foreign-key order (parents before children) with
// its full column list. id is copied verbatim; the schema's identity columns
// are GENERATED BY DEFAULT, so explicit ids are accepted.
var tables = []struct {
	name    string
	columns []string
}{
	{"album_jobs", []string{"id", "lidarr_album_id", "state", "candidates_tried", "next_attempt_at", "created_at", "updated_at", "title", "artist_name", "release_date", "artist_id"}},
	{"candidate_attempts", []string{"id", "album_job_id", "username", "score", "state", "fail_reason", "backoff_until", "created_at", "updated_at"}},
	{"transfers", []string{"id", "attempt_id", "slskd_id", "username", "filename", "state", "bytes_done", "bytes_total", "deadline", "last_progress_at", "updated_at", "retries"}},
	{"known_users", []string{"id", "username", "success_count", "fail_count", "last_success_at", "last_fail_at", "updated_at"}},
	{"artist_user_reliability", []string{"id", "artist_id", "user_id", "success_count", "fail_count", "last_success_at", "last_fail_at", "updated_at"}},
	{"job_events", []string{"id", "album_job_id", "event", "detail", "created_at"}},
}

// timestampColumns are scanned through sql.NullTime so SQLite's text
// timestamps convert cleanly to timestamptz on insert.
var timestampColumns = map[string]bool{
	"next_attempt_at":  true,
	"created_at":       true,
	"updated_at":       true,
	"backoff_until":    true,
	"deadline":         true,
	"last_progress_at": true,
	"last_success_at":  true,
	"last_fail_at":     true,
}

func main() {
	sqlitePath := flag.String("sqlite", "", "path to the existing slskdarr SQLite database")
	pgDSN := flag.String("pg", "", "PostgreSQL DSN of the migration target")
	flag.Parse()
	if *sqlitePath == "" || *pgDSN == "" {
		flag.Usage()
		os.Exit(2)
	}
	if err := run(*sqlitePath, *pgDSN); err != nil {
		log.Fatalf("migration failed: %v", err)
	}
}

func run(sqlitePath, pgDSN string) error {
	if _, err := os.Stat(sqlitePath); err != nil {
		return fmt.Errorf("sqlite database: %w", err)
	}

	// Apply the store schema to the target through the store package itself,
	// so the schema stays single-source.
	st, err := store.Open(pgDSN)
	if err != nil {
		return fmt.Errorf("open target and apply schema: %w", err)
	}
	st.Close()

	src, err := sql.Open("sqlite", sqlitePath)
	if err != nil {
		return fmt.Errorf("open sqlite: %w", err)
	}
	defer src.Close()

	dst, err := sql.Open("pgx", pgDSN)
	if err != nil {
		return fmt.Errorf("open postgres: %w", err)
	}
	defer dst.Close()

	// Safety: refuse to migrate into a target that already holds data.
	for _, t := range tables {
		var exists bool
		if err := dst.QueryRow(fmt.Sprintf(`SELECT EXISTS(SELECT 1 FROM %s)`, t.name)).Scan(&exists); err != nil {
			return fmt.Errorf("check target table %s: %w", t.name, err)
		}
		if exists {
			return fmt.Errorf("target table %s already has rows; refusing to migrate into a non-empty database", t.name)
		}
	}

	tx, err := dst.Begin()
	if err != nil {
		return fmt.Errorf("begin target transaction: %w", err)
	}
	defer tx.Rollback()

	counts := make(map[string]int)
	for _, t := range tables {
		n, err := copyTable(src, tx, t.name, t.columns)
		if err != nil {
			return fmt.Errorf("copy %s: %w", t.name, err)
		}
		counts[t.name] = n
	}

	// Reset each identity sequence past the copied ids. For an empty table,
	// setval(seq, 1, false) makes the next insert use 1; otherwise
	// setval(seq, MAX(id), true) makes it MAX(id)+1.
	for _, t := range tables {
		if _, err := tx.Exec(fmt.Sprintf(
			`SELECT setval(pg_get_serial_sequence('%s','id'), COALESCE(MAX(id), 1), MAX(id) IS NOT NULL) FROM %s`,
			t.name, t.name)); err != nil {
			return fmt.Errorf("reset %s id sequence: %w", t.name, err)
		}
	}

	if err := tx.Commit(); err != nil {
		return fmt.Errorf("commit: %w", err)
	}

	for _, t := range tables {
		log.Printf("migrated %s: %d rows", t.name, counts[t.name])
	}
	return nil
}

// copyTable streams every row of one table from SQLite into the target
// transaction, returning the number of rows copied. Timestamp columns are
// scanned into sql.NullTime so text timestamps convert to timestamptz; every
// other column passes through as a raw value.
func copyTable(src *sql.DB, tx *sql.Tx, name string, columns []string) (int, error) {
	colList := strings.Join(columns, ", ")
	rows, err := src.Query(fmt.Sprintf(`SELECT %s FROM %s`, colList, name))
	if err != nil {
		return 0, fmt.Errorf("read: %w", err)
	}
	defer rows.Close()

	placeholders := make([]string, len(columns))
	for i := range columns {
		placeholders[i] = fmt.Sprintf("$%d", i+1)
	}
	insert := fmt.Sprintf(`INSERT INTO %s (%s) VALUES (%s)`, name, colList, strings.Join(placeholders, ", "))
	stmt, err := tx.Prepare(insert)
	if err != nil {
		return 0, fmt.Errorf("prepare insert: %w", err)
	}
	defer stmt.Close()

	n := 0
	for rows.Next() {
		dests := make([]any, len(columns))
		for i, col := range columns {
			if timestampColumns[col] {
				dests[i] = new(sql.NullTime)
			} else {
				dests[i] = new(any)
			}
		}
		if err := rows.Scan(dests...); err != nil {
			return 0, fmt.Errorf("scan row: %w", err)
		}
		args := make([]any, len(columns))
		for i, col := range columns {
			if timestampColumns[col] {
				args[i] = *dests[i].(*sql.NullTime)
			} else {
				args[i] = *dests[i].(*any)
			}
		}
		if _, err := stmt.Exec(args...); err != nil {
			return 0, fmt.Errorf("insert row: %w", err)
		}
		n++
	}
	return n, rows.Err()
}
