// Every user-facing string lives here. Components must never inline text.
// This is i18n preparation, not i18n — see #86.
export const t = {
  app: {
    name: 'slskdarr',
    tagline: 'Lidarr → Soulseek',
  },
  nav: {
    overview: 'Overview',
    jobs: 'Jobs',
    events: 'Events',
    peers: 'Peers',
    health: 'Health',
    settings: 'Settings',
  },
  status: {
    queued: 'Queued',
    active: 'Active',
    stalled: 'Stalled',
    done: 'Done',
    failed: 'Failed',
    orphaned: 'Orphaned',
  },
  state: {
    WANTED: 'Wanted',
    SELECTING: 'Selecting candidate',
    DOWNLOADING: 'Downloading',
    IMPORTING: 'Importing',
    DONE: 'Done',
    FAILED: 'Failed',
    CANCELLED: 'Cancelled',
  },
  candidateState: {
    NEW: 'Not tried',
    ACTIVE: 'In progress',
    SUCCEEDED: 'Succeeded',
    FAILED: 'Failed',
  },
  event: {
    search: 'Searched',
    search_fallback: 'Searched (fallback)',
    candidate_selected: 'Candidate selected',
    candidate_rejected: 'Candidate rejected',
    attempt_failed: 'Attempt failed',
    attempt_succeeded: 'Attempt succeeded',
    transfer_stalled: 'Transfer stalled',
    import_ok: 'Import completed',
    import_rejected: 'Import rejected',
    job_failed: 'Job failed',
  },
  columns: {
    album: 'Album / Artist',
    peer: 'Peer',
    progress: 'Progress',
    status: 'Status',
    id: 'ID',
    time: 'Time',
    job: 'Job',
    event: 'Event',
    detail: 'Detail',
    module: 'Module',
    lastRun: 'Last attempt / status',
    score: 'Score',
    succeeded: 'Succeeded',
    failed: 'Failed',
  },
  jobs: {
    searchPlaceholder: 'Search artist, album, peer…',
    allStatuses: 'All',
    empty: 'No jobs match the current filter.',
    back: '← Back',
    cancel: 'Cancel',
    retry: 'Retry',
    attemptHistory: 'Attempt history',
    events: 'Events',
    loading: 'Loading…',
    noAttempts: 'No attempts yet.',
    noEvents: 'No events.',
    cancelFailed: 'Could not cancel the job. It may already have finished.',
    retryFailed: 'Could not retry the job. Only failed jobs can be retried.',
    sleepingUntil: (time: string) => `Sleeping until ${time}`,
    candidates: (tried: number, max: number) => `${tried} of ${max} candidates tried`,
  },
  events: {
    filterPlaceholder: 'Filter events…',
    empty: 'No events.',
  },
  peers: {
    empty: 'No peers recorded yet.',
    noArtistHistory: 'No artist-specific history.',
    artistLine: (id: number, score: string, ok: number, fail: number) =>
      `Artist #${id} — score ${score}, ${ok} succeeded, ${fail} failed`,
  },
  health: {
    neverRun: 'Never run',
    consecutiveFailures: (n: number) => `${n} consecutive failures`,
  },
  settings: {
    readOnlyNotice:
      'Settings are read from the configuration file. Editing them here is planned — see issue #89.',
    lidarr: 'Lidarr',
    url: 'URL',
    apiKey: 'API key',
    apiKeyHidden: 'Configured (hidden)',
    apiKeyMissing: 'Not configured',
    reconcile: 'Reconcile',
    interval: 'Interval',
    concurrentDownloads: 'Concurrent downloads',
  },
} as const;
